// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CfgSpace
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GameConstCfgs : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_11_23(); }
  public static GameConstCfgs GetRootAsGameConstCfgs(ByteBuffer _bb) { return GetRootAsGameConstCfgs(_bb, new GameConstCfgs()); }
  public static GameConstCfgs GetRootAsGameConstCfgs(ByteBuffer _bb, GameConstCfgs obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GameConstCfgs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CfgSpace.GameConstCfg? GameConstCfgArray(int j) { int o = __p.__offset(4); return o != 0 ? (CfgSpace.GameConstCfg?)(new CfgSpace.GameConstCfg()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int GameConstCfgArrayLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<CfgSpace.GameConstCfgs> CreateGameConstCfgs(FlatBufferBuilder builder,
      VectorOffset gameConstCfgArrayOffset = default(VectorOffset)) {
    builder.StartTable(1);
    GameConstCfgs.AddGameConstCfgArray(builder, gameConstCfgArrayOffset);
    return GameConstCfgs.EndGameConstCfgs(builder);
  }

  public static void StartGameConstCfgs(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddGameConstCfgArray(FlatBufferBuilder builder, VectorOffset gameConstCfgArrayOffset) { builder.AddOffset(0, gameConstCfgArrayOffset.Value, 0); }
  public static VectorOffset CreateGameConstCfgArrayVector(FlatBufferBuilder builder, Offset<CfgSpace.GameConstCfg>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateGameConstCfgArrayVectorBlock(FlatBufferBuilder builder, Offset<CfgSpace.GameConstCfg>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateGameConstCfgArrayVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<CfgSpace.GameConstCfg>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateGameConstCfgArrayVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<CfgSpace.GameConstCfg>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartGameConstCfgArrayVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<CfgSpace.GameConstCfgs> EndGameConstCfgs(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CfgSpace.GameConstCfgs>(o);
  }
  public static void FinishGameConstCfgsBuffer(FlatBufferBuilder builder, Offset<CfgSpace.GameConstCfgs> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedGameConstCfgsBuffer(FlatBufferBuilder builder, Offset<CfgSpace.GameConstCfgs> offset) { builder.FinishSizePrefixed(offset.Value); }
}


}
